//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VehicleInsuranceManagement.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.OrderPolicies = new HashSet<OrderPolicy>();
        }

        [Display(Name = "Vehicle ID")]
        public int VehicleID { get; set; }

        [Display(Name = "Type ID")]
        [Required(ErrorMessage = "Type ID is required")]
        public int VehicleTypeID { get; set; }

        [Display(Name = "Model ID")]
        [Required(ErrorMessage = "Model ID is required")]
        public int VehicleModelID { get; set; }

        [Display(Name = "Customer ID")]
        public int CustomerID { get; set; }

        [Display(Name = "Owner")]
        [Required(ErrorMessage = "Owner is required")]
        public string VehicleOwnerName { get; set; }

        [Display(Name = "Body Number")]
        [RegularExpression("[0-9A-Z]{9,17}", ErrorMessage = "Body Number invalid (Ex: C20SED112342)")]
        [Required(ErrorMessage = "Body Number is required")]
        public string VehicleBodyNumber { get; set; }

        [Display(Name = "Engine Number")]
        [Required(ErrorMessage = "Engine Number is required")]
        [RegularExpression("[0-9A-Z]{9,17}", ErrorMessage = "Engine Number invalid (Ex: VAVMZ2H00460)")]
        public string VehicleEngineNumber { get; set; }

        [Display(Name = "Vehicle Number")]
        [Required(ErrorMessage = "Vehicle Number is required")]
        [RegularExpression("[1-9][0-9][A-Z]-[0-9]{4,5}", ErrorMessage = "Vehicle Number invalid (Ex: 96A-01719)")]
        public string VehicleNumber { get; set; }

        [Display(Name = "Image")]
        [DataType(DataType.Upload)]
        public byte[] Image { get; set; }

        [Display(Name = "Seat Number")]
        [Required(ErrorMessage = "Seat Number is required")]
        public int SeatNumber { get; set; }

        [Display(Name = "Status")]
        public string Status { get; set; }

        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPolicy> OrderPolicies { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        public virtual VehicleModel VehicleModel { get; set; }
    }
}